IP_ADDR_SERVIDOR = '0.0.0.0'
PORTA_SERVIDOR = 80
NOME_ARQUIVO_DATABASE = "database.db"
TAMANHO_MINIMO_NOME_ONG = 8
TAMANHO_MINIMO_NOME_USUARIO = 2
TAMANHO_MINIMO_SOBRENOME_USUARIO = 2
TAMANHO_MINIMO_LOGIN_USUARIO = 8
TAMANHO_MINIMO_SENHA_USUARIO = 8

STATIC_URL_PATH = "views"

CODIGOS_HTTP = {
    "Ok": 200,
    "Created": 201,
    "Unauthorized": 401,
    "Not Found": 404,
    "Internal Server Error": 500
}
